env:
  browser: true
  es2021: true
  node: true
extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]


plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

plugins:
  - fp

extends:
  - "airbnb-base"
  - "plugin:fp/recommended"

env:
  node: true
  es2020: true

parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0
  fp/no-loops: 0
  fp/no-nil: 0
  fp/no-unused-expression: 0
  fp/no-let: 0
  fp/no-throw: 0
  fp/no-mutation: 0
  fp/no-mutating-methods: 0